CC = gcc
OUTPUT1 = readbuf
INPUT1 = readbuf.c
OUTPUT2 = writebuf
INPUT2 = writebuf.c
OUTPUT = main
INPUT = main.c

all:
	$(CC) -o $(OUTPUT1) -g $(INPUT1) 
	$(CC) -o $(OUTPUT2) -g $(INPUT2) 
	$(CC) -o $(OUTPUT) -g $(INPUT) 
	
